<a href="https://colab.research.google.com/github/taciturn02/CreditCardFruadDetection/blob/main/creditCard_fraudDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [4]:
train_df = pd.read_csv("/content/drive/MyDrive/CreditCard_DataSet/randomUndersammpledData.csv")
train_df2 = pd.read_csv("/content/drive/MyDrive/CreditCard_DataSet/randomOversampledData.csv")

In [5]:
train_df.info()
train_df2.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4290 entries, 0 to 4289
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   merchant    4290 non-null   int64  
 1   category    4290 non-null   int64  
 2   amt         4290 non-null   float64
 3   gender      4290 non-null   int64  
 4   lat         4290 non-null   float64
 5   long        4290 non-null   float64
 6   city_pop    4290 non-null   int64  
 7   merch_lat   4290 non-null   float64
 8   merch_long  4290 non-null   float64
 9   is_fraud    4290 non-null   int64  
 10  hour        4290 non-null   int64  
 11  day         4290 non-null   int64  
 12  month       4290 non-null   int64  
 13  age_cust    4290 non-null   int64  
dtypes: float64(5), int64(9)
memory usage: 469.3 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1107148 entries, 0 to 1107147
Data columns (total 14 columns):
 #   Column      Non-Null Count    Dtype  
---  ------      ------------

Split data into target and features

In [6]:
X = train_df.drop(columns='is_fraud', axis=1)
Y = train_df['is_fraud']

XX = train_df2.drop(columns='is_fraud', axis=1)
YY = train_df2['is_fraud']

In [7]:
print(X)
print(XX)

      merchant  category      amt  gender      lat      long  city_pop  \
0          593        11    25.01       0  38.4549 -122.2564     94014   
1          680         6    28.34       0  40.7320  -73.1000      4056   
2          481         6    82.90       1  39.4584 -106.3851       277   
3          285         2    72.01       1  35.6665  -97.4798    116001   
4          170         1     4.43       0  41.1826  -92.3097      1583   
...        ...       ...      ...     ...      ...       ...       ...   
4285       670        12  1041.51       1  34.6323  -89.8855     14462   
4286       349        12   868.09       1  34.6323  -89.8855     14462   
4287       443        11  1039.42       1  34.6323  -89.8855     14462   
4288        29         4   289.27       1  34.6323  -89.8855     14462   
4289       281         8   766.38       1  34.6323  -89.8855     14462   

      merch_lat  merch_long  hour  day  month  age_cust  
0     38.827746 -122.743534    15    2     12        

In [8]:
print(Y)
print(YY)

0       0
1       0
2       0
3       0
4       0
       ..
4285    1
4286    1
4287    1
4288    1
4289    1
Name: is_fraud, Length: 4290, dtype: int64
0          1
1          1
2          1
3          1
4          1
          ..
1107143    0
1107144    0
1107145    0
1107146    0
1107147    0
Name: is_fraud, Length: 1107148, dtype: int64


Split Data into training data and testing data

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.40, stratify=Y, random_state=42)
XX_train, XX_test, YY_train, YY_test = train_test_split(XX, YY, test_size=0.40, stratify=YY, random_state=42)

In [10]:
print(X.shape, X_train.shape, X_test.shape)
print(XX.shape, XX_train.shape, XX_test.shape)

(4290, 13) (2574, 13) (1716, 13)
(1107148, 13) (664288, 13) (442860, 13)


##MODEL TRAINING

In [11]:
model = LogisticRegression()

In [12]:
model.fit(X_train, Y_train)
model.fit(XX_train, YY_train)

LogisticRegression()

MODEL EVALUATION

In [13]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [14]:
print('Accuracy on Training  Undersampled  Data: ', training_data_accuracy)

Accuracy on Training  Undersampled  Data:  0.8566433566433567


In [15]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [16]:
print('Accuracy score on Test UnderSampled Data : ', test_data_accuracy)

Accuracy score on Test UnderSampled Data :  0.8432400932400932


In [17]:
XX_train_prediction = model.predict(XX_train)
training_data_accuracy = accuracy_score(XX_train_prediction, YY_train)

In [18]:
print('Accuracy on Training  OverSampled  Data: ', training_data_accuracy)

Accuracy on Training  OverSampled  Data:  0.8501403005925141


In [19]:
XX_test_prediction = model.predict(XX_test)
test_data_accuracy = accuracy_score(XX_test_prediction, YY_test)

In [20]:
print('Accuracy score on Test Oversampled Data : ', test_data_accuracy)

Accuracy score on Test Oversampled Data :  0.8505419319875356


##DECISION TREE MODEL

In [21]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix


In [22]:
def model_testing1(estimator):
    ## Prediction on data
    y_preds = estimator.predict(X_test)

    ##Print accuracy score
    print("Accuracy Score on UnderSampled Test Data: ",accuracy_score(Y_test,y_preds))

    ## Print classification report
    print("\nConfussion Matrix  of UnderSampled Test Data:\n " ,confusion_matrix(Y_test ,y_preds),"\n")

    ## Check confusion matrix
    print("classification_report of UnderSampled Test Data: \n\n",classification_report(Y_test ,y_preds))

In [23]:
def model_testing11(estimator):
    ## Prediction on data
    y_preds = estimator.predict(X_train)

    ##Print accuracy score
    print("Accuracy Score on UnderSampled Train Data: ",accuracy_score(Y_train,y_preds))

    ## Print classification report
    print("\nConfussion Matrix  of UnderSampled Train Data:\n " ,confusion_matrix(Y_train ,y_preds),"\n")

    ## Check confusion matrix
    print("classification_report of UnderSampled Train Data: \n\n",classification_report(Y_train ,y_preds))

In [24]:
dt = DecisionTreeClassifier(criterion = 'entropy',max_depth = 6, random_state=42)
dt.fit(X_train ,Y_train)
model_testing1(dt)


Accuracy Score on UnderSampled Test Data:  0.9458041958041958

Confussion Matrix  of UnderSampled Test Data:
  [[824  34]
 [ 59 799]] 

classification_report of UnderSampled Test Data: 

               precision    recall  f1-score   support

           0       0.93      0.96      0.95       858
           1       0.96      0.93      0.95       858

    accuracy                           0.95      1716
   macro avg       0.95      0.95      0.95      1716
weighted avg       0.95      0.95      0.95      1716



In [25]:
dt = DecisionTreeClassifier(criterion = 'entropy',max_depth = 6, random_state=42)
dt.fit(X_train ,Y_train)
model_testing11(dt)


Accuracy Score on UnderSampled Train Data:  0.958041958041958

Confussion Matrix  of UnderSampled Train Data:
  [[1241   46]
 [  62 1225]] 

classification_report of UnderSampled Train Data: 

               precision    recall  f1-score   support

           0       0.95      0.96      0.96      1287
           1       0.96      0.95      0.96      1287

    accuracy                           0.96      2574
   macro avg       0.96      0.96      0.96      2574
weighted avg       0.96      0.96      0.96      2574



In [26]:
def model_testing2(estimator):
    ## Prediction on data
    y_preds = estimator.predict(XX_test)

    ##Print accuracy score
    print("Accuracy Score on OverSampled Test Data: ",accuracy_score(YY_test,y_preds))

    ## Print classification report
    print("\nConfussion Matrix  of OverSampled Test Data:\n " ,confusion_matrix(YY_test ,y_preds),"\n")

    ## Check confusion matrix
    print("classification_report of OverSampled Test Data: \n\n",classification_report(YY_test ,y_preds))

In [27]:
def model_testing22(estimator):
    ## Prediction on data
    y_preds = estimator.predict(XX_train)

    ##Print accuracy score
    print("Accuracy Score on OverSampled Train Data: ",accuracy_score(YY_train,y_preds))

    ## Print classification report
    print("\nConfussion Matrix  of OverSampled Train Data:\n " ,confusion_matrix(YY_train ,y_preds),"\n")

    ## Check confusion matrix
    print("classification_report of OverSampled Train Data: \n\n",classification_report(YY_train ,y_preds))

In [28]:
dt = DecisionTreeClassifier(criterion = 'entropy', max_depth = 6, random_state=42)
dt.fit(XX_train ,YY_train)
model_testing2(dt)


Accuracy Score on OverSampled Test Data:  0.9551099670324708

Confussion Matrix  of OverSampled Test Data:
  [[213380   8050]
 [ 11830 209600]] 

classification_report of OverSampled Test Data: 

               precision    recall  f1-score   support

           0       0.95      0.96      0.96    221430
           1       0.96      0.95      0.95    221430

    accuracy                           0.96    442860
   macro avg       0.96      0.96      0.96    442860
weighted avg       0.96      0.96      0.96    442860



In [29]:
dt = DecisionTreeClassifier(criterion = 'entropy', max_depth = 6, random_state=42)
dt.fit(XX_train ,YY_train)
model_testing22(dt)


Accuracy Score on OverSampled Train Data:  0.954825316730093

Confussion Matrix  of OverSampled Train Data:
  [[320056  12088]
 [ 17921 314223]] 

classification_report of OverSampled Train Data: 

               precision    recall  f1-score   support

           0       0.95      0.96      0.96    332144
           1       0.96      0.95      0.95    332144

    accuracy                           0.95    664288
   macro avg       0.95      0.95      0.95    664288
weighted avg       0.95      0.95      0.95    664288



##RANDOM FOREST MODEL

In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(criterion = 'entropy',max_depth = 8, random_state=42)
classifier.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', max_depth=8, random_state=42)

In [31]:
model_testing1(classifier)


Accuracy Score on UnderSampled Test Data:  0.9487179487179487

Confussion Matrix  of UnderSampled Test Data:
  [[838  20]
 [ 68 790]] 

classification_report of UnderSampled Test Data: 

               precision    recall  f1-score   support

           0       0.92      0.98      0.95       858
           1       0.98      0.92      0.95       858

    accuracy                           0.95      1716
   macro avg       0.95      0.95      0.95      1716
weighted avg       0.95      0.95      0.95      1716



In [32]:
model_testing11(classifier)

Accuracy Score on UnderSampled Train Data:  0.9766899766899767

Confussion Matrix  of UnderSampled Train Data:
  [[1283    4]
 [  56 1231]] 

classification_report of UnderSampled Train Data: 

               precision    recall  f1-score   support

           0       0.96      1.00      0.98      1287
           1       1.00      0.96      0.98      1287

    accuracy                           0.98      2574
   macro avg       0.98      0.98      0.98      2574
weighted avg       0.98      0.98      0.98      2574



In [33]:
classifier.fit(XX_train,YY_train)

RandomForestClassifier(criterion='entropy', max_depth=8, random_state=42)

In [34]:
model_testing2(classifier)
classifier.score(XX_test ,YY_test)

Accuracy Score on OverSampled Test Data:  0.963476042090051

Confussion Matrix  of OverSampled Test Data:
  [[216613   4817]
 [ 11358 210072]] 

classification_report of OverSampled Test Data: 

               precision    recall  f1-score   support

           0       0.95      0.98      0.96    221430
           1       0.98      0.95      0.96    221430

    accuracy                           0.96    442860
   macro avg       0.96      0.96      0.96    442860
weighted avg       0.96      0.96      0.96    442860



0.963476042090051

In [35]:
model_testing22(classifier)


Accuracy Score on OverSampled Train Data:  0.9633953947685341

Confussion Matrix  of OverSampled Train Data:
  [[325018   7126]
 [ 17190 314954]] 

classification_report of OverSampled Train Data: 

               precision    recall  f1-score   support

           0       0.95      0.98      0.96    332144
           1       0.98      0.95      0.96    332144

    accuracy                           0.96    664288
   macro avg       0.96      0.96      0.96    664288
weighted avg       0.96      0.96      0.96    664288

